CREATE TABLE IF NOT EXISTS BOOK (
    Isbn      CHAR(10) PRIMARY KEY,
    Title     VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORS (
    Author_id INTEGER PRIMARY KEY,
    Name      VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK_AUTHORS (
    Author_id INTEGER NOT NULL,
    Isbn      CHAR(10) NOT NULL,
    PRIMARY KEY (Author_id, Isbn),
    FOREIGN KEY (Author_id) REFERENCES AUTHORS(Author_id),
    FOREIGN KEY (Isbn)      REFERENCES BOOK(Isbn)
);

CREATE TABLE IF NOT EXISTS BORROWER (
    Card_id   INTEGER PRIMARY KEY,
    Ssn       CHAR(11) NOT NULL UNIQUE,
    Bname     VARCHAR(255) NOT NULL,
    Address   VARCHAR(255) NOT NULL,
    Phone     VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS BOOK_LOANS (
    Loan_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    Isbn      CHAR(10) NOT NULL,
    Card_id   INTEGER NOT NULL,
    Date_out  DATE NOT NULL,
    Due_date  DATE NOT NULL,
    Date_in   DATE,
    FOREIGN KEY (Isbn)    REFERENCES BOOK(Isbn),
    FOREIGN KEY (Card_id) REFERENCES BORROWER(Card_id)
);

CREATE TABLE IF NOT EXISTS FINES (
    Loan_id   INTEGER PRIMARY KEY,
    Fine_amt  DECIMAL(7,2) NOT NULL,
    Paid      INTEGER NOT NULL CHECK (Paid IN (0,1)),
    FOREIGN KEY (Loan_id) REFERENCES BOOK_LOANS(Loan_id)
);
